# Fichier de configuration COMPLET et CORRIGÉ pour Netlify

[build]
  # Ce dossier contient vos fonctions serverless.
  functions = "api"

  # Ce dossier contient les fichiers de votre site à publier.
  publish = "."


# -- SECTION MANQUANTE ET CRUCIALE AJOUTÉE CI-DESSOUS --
# Cette règle de redirection est la "colle" magique.
# Elle dit à Netlify : "Quand le navigateur demande une page dans /api/...,
# ne cherche pas un fichier, mais exécute la fonction correspondante."
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200